### ISSUE TITLE
Random test failure with 'dereference broken links'

### ISSUE THREAD

**Issue by wickedest** [danieldietrich/copy#14]
This test randomly fails (maybe about 10% of the time): _Should fail when trying to dereference broken links_

The issue is that it is a race condition.  Sometimes l3 resolves before l1, and does not match the expected exception:

```js
ENOENT: no such file or directory, copyfile '__tmp/src/d1/d3/l3' -> '__tmp/dst/d1/d3/l3'
```

**Comment by danieldietrich** [comment]
Thanks Jamie! I wasn't able to reproduce it on my local machine but it makes absolutely sense!

The main cause for the unpredictable execution order (which is OK!) is the `Promise.all` part of the following code:

<img width="1232" alt="Screenshot 2019-12-22 at 20 34 33" src="https://user-images.githubusercontent.com/743833/71326391-91841d80-24fa-11ea-8fd9-4f7194196314.png">

The message is: our tests should generally not rely on any kind of execution order. I will fix the unit tests.

---

Some thoughts that are not directly related to this issue:

Important for the correctness of the _copy_ library is, that the copy function finishes only and only if all recursive sub-tasks finished successfully or when the first error occurred. In fact, there exists no unit test that ensures that no further sub-task is started after the first error occurred. But because of the unpredictable order of execution it is hard to test that in a unit test. Nevertheless, if we internally only use Promise.all and not Promise.allSettled, that should be the case.

**Comment by danieldietrich** [comment]
Interesting. I reopened the issue because now I have sporadic test problems after upgrading npm, node and some dev dependencies. I will investigate that...

**Comment by danieldietrich** [comment]
It seems to be solved. I can't find any code that would lead to a race condition. I removed one update command and checked different node version. After that I ran the tests using more than 50 times in bash, zsh on a macOS terminal and on an emulated VS Code terminal. All tests were green.
