### ISSUE TITLE
Feature request for post-copy option

### ISSUE THREAD

**Issue by wickedest** [danieldietrich/copy#18]
I need to do a post copy command, `chmod`.  While it could be provided like the other options `chown` or `chgrp`, I only need to apply it to selected files and those options apply to all files.  Having a callback after each file is copied would enable post copy actions.  Some suggestions on the option might be: "copied", or "afterEach".  Such an option could also allow logging out the file name that was created.  So, "target" and "targetStats" would be useful to have as arguments.

**Comment by danieldietrich** [comment]
Thanks for the feature suggestion, I like it!

### Naming

The name `afterEach` is appropriate, let's take it. The function signature will be:

```ts
{
    afterEach?: (source: string, target: string, sourceStats: fs.Stats, targetStats: fs.Stats | undefined) => void | Promise<void>
}
```

### Dry run

`forEach` does return nothing, that means it will perform side-effects by changing the outer world, e.g. by writing logs, changing the file system, etc. Because of that, the only viable solution is not to call `forEach` in a dry-run.

### Deprecate chown and chgrp

As you mentioned, `chown` and `chgrp` are closely related to `chmod`. All of them can be easily achieved using `afterEach`:

```ts
const lchown = fs.promises.lchown;

async function example(src: string, dst: string, uid: number) {
    copy(src, dst, {
        afterEach: async (source, target, sourceStats, targetStats) => {
            await lchown(target, uid, sourceStats.gid);
        }
    });
}
```

Therefore I think we should deprecate the `chown` and `chgrp` options in the next minor release 0.4.0 and remove them in the next major release 1.0.0.

**Comment by wickedest** [comment]
Thanks for the quick response! I think the proposed depreciation makes sense, it makes the options simpler. Though, it isn't great that it won't be called in a dry-run. I'd have said to pass in the option and let the developer decide.
