### ISSUE TITLE
Rename file while transforming

### ISSUE THREAD

**Issue by wickedest** [danieldietrich/copy#6]
I was looking for a replacement for [ncp](https://www.npmjs.com/package/ncp) (which has issues and is unmaintained), and I came across **copy**, which initially looked perfect.  However, I need to transform some files and rename them while copying.  E.g. "package.json.tmpl" => transform => and output "package.json".

I think it could be a useful feature to add.  Best way I can think of is to add a new rename option:
```js
rename(source: string, target: string, sourceStats: fs.Stats, targetStats: fs.Stats | undefined) => string|undefined
```

The idea would be that if you want to rename a target, return a string.  The stats give more fine-grained control, e.g. if a file exists, maybe you want to add a .1 extension.  I'd be great if you could add this (or accept a PR), otherwise, I'll keep looking...

**Comment by danieldietrich** [comment]
Thank you, I also thought about adding a **rename** option. I will take a look later today and review your PR.

**Comment by wickedest** [comment]
@danieldietrich - much appreciated!  One thing that struck me after submitting this PR is that, arguably, the rename could also be applied to directories too (not just files, symlinks).  Looking back at it with that in mind, perhaps the rename should be applied once in `cpPath`.  If that's feasible, then it'd be much cleaner.

**Comment by danieldietrich** [comment]
Yes, I stumbled also into that. Symlinks are relative paths, I still need a bit time to fiddle around with it...

**Comment by wickedest** [comment]
I started playing around with that idea, but I think you should know I'm seeing random failures.  Be sure to test several times.

**Comment by danieldietrich** [comment]
When designing the 'copy' library, I considered adding the _rename_ functionality. However, on the one hand, I find it hard to provide a good API. On the other hand, I find it hard to carry recursively path transformations that are applied to a parent path.

In particular, I see two variants

1. the full fledged solution, which includes the transformation of whole directory structures
2. the simplified version, which only allows to rename specific directories, files and links while preserving the overall directory structure

The second variant exists only because the first variant is considered to be too complex to implement. Additionally, it looks like renaming is hard to be handled on the use-site when dealing with absolute and relative paths. There might be the need to provide some syntactic sugar (in form of an additional library?) in order to transform paths.

When creating the library, I was in doubt what the best solution is. My motto: if in doubt, leave it away.

## Variant 1: Allowing to change the overall directory structure

Source structure ('d' = directory, 'f' = file, 'l' = symlink):

```
src
├── d1
│   ├── d3
│   │   ├── f3
│   │   ├── l1 -> ../l1
│   │   └── l3 -> ../l2
│   ├── d4
│   │   ├── f4
│   │   ├── l4 -> ../l1
│   │   └── l5 -> ../l2
│   ├── f1
│   └── l2 -> d3/l1
├── d2
│   └── f2
└── d3
```

Renaming directories:

```
src/d1 -> dst/D4/D5
src/d1/d3 -> dst/D6
```

Copy result:

```
dst
├── d2
│   └── f2
├── d3
├── D4
│   └── D5
│       ├── d4
│       │   ├── f4
│       │   ├── l4 -> ../l1
│       │   └── l5 -> ../l2
│       ├── f1
│       └── l2 -> ../d5/l1
└── D6
    ├── f3
    ├── l1 -> ../D4/D5/l1
    └── l3 -> ../D4/D5/l2
```

## Variant 2: Only allow to rename the current dir/file/link name while preserving the directory structure 

```
src
├── d1
│   ├── d3
│   │   ├── f3
│   │   ├── l1 -> ../l1
│   │   └── l3 -> ../l2
│   ├── f1
│   └── l2 -> d3/l1
├── d2
│   └── f2
└── d3
```

Renaming directories:

```
src/d1 -> D5
src/d1/d3 -> D6
src/d2/f2 -> F3
```

Copy result:

```
src
├── D5
│   ├── D6
│   │   ├── f3
│   │   ├── l1 -> ../l1
│   │   └── l3 -> ../l2
│   ├── f1
│   └── l2 -> d3/l1
├── d2
│   └── F3
└── d3
```

I will check, if there is a good way to implement Variant 1.

**Comment by danieldietrich** [comment]
We will go for the simplest solution by 'just' providing a new name for a path. That is the common use case.

We will not add additional logic, such as rewriting symlink locations etc. Changing contents (such as relative symlink targets) should be the responsibility of the transform function.

I'm preparing an additional PR.

**Comment by danieldietrich** [comment]
@wickedest I will create a few housekeeping PRs and then release a new version to npm today. Thank you for using the `copy` library!
